accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name='login'),
    path("logout/", views.logout, name='logout'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:review_pk>/", views.detail, name="detail"),
    path("<int:review_pk>/update/", views.update, name="update"),
    path("<int:review_pk>/delete/", views.delete, name="delete"),
    path("<int:review_pk>/comments/", views.comment_create, name="comment_create"),
    path(
        "<int:review_pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path("search/", views.search, name="search"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    pass

reviews/models.py
from distutils.text_file import TextFile
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    content = models.TextField()
    movie_name = models.CharField(max_length=80)
    grade_Choices = (
        ("⭐", "⭐"),
        ("⭐⭐", "⭐⭐"),
        ("⭐⭐⭐", "⭐⭐⭐"),
        ("⭐⭐⭐⭐", "⭐⭐⭐⭐"),
        ("⭐⭐⭐⭐⭐", "⭐⭐⭐⭐⭐"),
    )
    grade = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()

accounts/forms.py
from webbrowser import get
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "email", "password1", "password2")

reviews/forms.py
from tkinter import Widget
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "movie_name",
            "title",
            "content",
            "grade",
        ]
        labels = {"title": "제목", "content": "내용", "movie_name": "영화 제목", "grade": "평점"}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]
        widgets = {
            "content": forms.Textarea(attrs={"class": "from-control", "rows": 1}),
        }
        labels = {
            "content": "댓글",
        }

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("reviews:index")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "reviews:index")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("reviews:index")

reviews/views.py
from django.shortcuts import render, redirect
from .models import Review, Comment
from .forms import ReviewForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from reviews.forms import ReviewForm
from reviews.models import Review
from django.db.models import Q
from urllib.parse import urlparse
from urllib.request import urlopen

# Create your views here.
def index(request):
    reviews = Review.objects.order_by("-pk")
    context = {
        "reviews": reviews,
    }
    return render(request, "reviews/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()
            messages.success(request, "글 작성이 완료되었습니다.")
            return redirect("reviews:index")
    else:
        review_form = ReviewForm()
    context = {
        "review_form": review_form,
    }
    return render(request, "reviews/create.html", context)


def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    comment_form = CommentForm()
    context = {
        "review": review,
        "comment_form": comment_form,
    }

    return render(request, "reviews/detail.html", context)


@login_required
def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user:
        if request.method == "POST":
            review_form = ReviewForm(request.POST, instance=review)
            if review_form.is_valid():
                review.save()
                return redirect("reviews:detail", review.pk)
        else:
            review_form = ReviewForm(instance=review)
    else:
        return redirect("reviews:index")
    context = {"review_form": review_form}
    return render(request, "reviews/update.html", context)


@login_required
def delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == "POST":
        if request.user == review.user:
            review.delete()
            return redirect("reviews:index")
    return redirect("reviews:detail", review.pk)


@login_required
def comment_create(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review = review
            comment.user = request.user
            comment.save()
            return redirect("reviews:detail", review.pk)
    return redirect("reviews:detail", review.pk)


@login_required
def comment_delete(request, review_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if comment.user == request.user:
        if request.method == "POST":
            comment.delete()
            return redirect("reviews:detail", review_pk)
    return redirect("reviews:detail", review_pk)


def search(request):
    all_data = Review.objects.order_by("-pk")
    search = request.GET.get("search", "")
    if search:
        search_list = all_data.filter(
            Q(title__icontains=search) | Q(movie_name__icontains=search)
        )

        context = {
            "search_list": search_list,
        }
    else:
        context = {
            "search_list": all_data,
        }

    return render(request, "reviews/search.html", context)

accounts/templates/accounts/login.html
{% extends "base.html" %} 
{% load django_bootstrap5 %} 
{% bootstrap_css %} 
{% bootstrap_javascript %} 
{% block content %} 
<div class="container mt-3">
<form action="" method="POST">
  {% csrf_token %} 
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="로그인" %}
  <a href="{% url 'accounts:signup' %}">회원가입</a>
</form>
</div> 
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %} 
{% load django_bootstrap5 %} 
{% bootstrap_css %} 
{% bootstrap_javascript %} 
{% block content %} 
<div class="container mt-3">
<form action="" method="POST">
  {% csrf_token %} 
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="가입" %}
</form>
</div> 
{% endblock %}

reviews/templates/reviews/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
  <div class="m-5 p-3 border border-3 border-dark rounded">
    {% if request.resolver_match.url_name == 'create' %}
      <h1 class="my-3">
        글쓰기
      </h1>
    {% else %}
      <h1>
        수정하기
      </h1>
    {% endif %}

    <form action="{% url 'reviews:create' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form review_form %}
      <input type="submit" value="작성">
    </form>
  </div>
{% endblock %}

reviews/templates/reviews/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
  <div class="container mt-5 border border-3 border-dark rounded">
    <h1 class="my-3">영화 제목 :
      {{ review.movie_name }}
    </h1>
    <div class="d-flex justify-content-between">
    <span>작성자 :{{ review.user.username }}</span>    
    <span>
    {% if review.grade == 5 %}
                ⭐⭐⭐⭐⭐
              {% elif review.grade == 4 %}
                ⭐⭐⭐⭐
              {% elif review.grade == 3 %}
                ⭐⭐⭐
              {% elif review.grade == 2 %}
                ⭐⭐
              {% elif review.grade == 1 %}
                ⭐
              {% endif %}
            </span>               
    </div>  
    <hr>  
    <p>제목 :
      {{ review.title }}</p>
    <hr>  
    <p>내용 :
      {{ review.content }}</p>
    <hr>  
    <p>작성시간 :
      {{ review.created_at|date:'y.m.d H:i' }}</p>
    <hr>    
    <p>수정시간 :
      {{ review.updated_at|date:'y.m.d H:i' }}</p>
    <hr>    

    {% if request.user == review.user %}
      <div class="d-flex">
        <a href="{% url 'reviews:update' review.pk %}"><input type="submit" class="btn btn-warning " value="수정하기"></a>
        <form action="{% url 'reviews:delete' review.pk %}" method="POST">
          {% csrf_token %}
          <input type='submit' class='btn btn-danger mx-2' value='삭제하기'>
        </form>
      </div>
    {% endif %}

    {% if request.user.is_authenticated %}
      <div class="my-2">
        <form action="{% url 'reviews:comment_create' review.pk %}" method="POST">
          {% csrf_token %}
          {% bootstrap_form comment_form %}
          <input type="submit" value="댓글 작성">
        </form>
      </div>
    {% endif %}
    <hr>
    {% for comment in review.comment_set.all %}
    <div class="d-flex">
      <p>{{ comment.user.username }}
        |
        {{ comment.content }}</p>
      {% if request.user == comment.user %}
        <form action="{% url 'reviews:comment_delete' review.pk comment.pk%}" method="POST">
          {% csrf_token %}
          <input type="submit" value="DELETE">
        </form>
      {% endif %}
    </div>
    {% endfor %}
  </div>
{% endblock %}

reviews/templates/reviews/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
  <div class="container">
    <h1 class="my-2">리뷰 목록</h1>
    {% if request.user.is_authenticated %}
      <a class="btn btn-primary my-3 float-right" href="{% url 'reviews:create' %}">글 쓰기</a>
    {% endif %}

    <div class="row">
      {% for review in reviews %}
        <div class="col-4 my-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ review.title }}
                |
                {{ review.user.username }}</h5>
              <a href="{% url 'reviews:detail' review.pk %}" class="btn btn-outline-primary my-3">복습하기</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

reviews/templates/reviews/update.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
  {% if request.resolver_match.url_name == 'create' %}
    <h1>
      글쓰기
    </h1>
  {% else %}
    <h1>
      수정하기
    </h1>
  {% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form review_form %}
    <input type="submit" value="수정하기">
  </form>
{% endblock %}

templates/base.html
{% load django_bootstrap5 %}
{% load static%}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body style="background-color: #e3f2fd;">
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark ">
      <div class="container-fluid">
        <div>
          <a class="navbar-brand" href="{% url 'reviews:index' %}">LOGO</a>
          <span class='text-light'>{{ request.user.username }}</span>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}" tabindex="-1" aria-disabled="true">로그아웃</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'reviews:create' %}" tabindex="-1" aria-disabled="true">리뷰 작성</a>
              </li>

            {% else %}

              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}" tabindex="-1" aria-disabled="true">로그인</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}" tabindex="-1" aria-disabled="true">회원가입</a>
              </li>
            {% endif %}
          </ul>
          <form class="d-flex" role="search" action="{% url 'reviews:search' %}">
            <input class="form-control me-2" type="search" placeholder="Search" name="search" aria-label="Search">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock %}

    <footer class="bg-dark text-white text-center mt-5 fixed-bottom">
      Django PJT, by 이호빈, 조창현, 이주용
    </footer>

  </body>

</html>